[package]
authors = ["Jake Goulding <jake.goulding@gmail.com>"]
name = "example"
version = "0.1.0"

[dependencies]
env_logger = "0.3.5"
iron = "0.4.0"

[dependencies.playground-middleware]
path = ".."
