[package]
authors = ["Jake Goulding <jake.goulding@gmail.com>"]
name = "staticfile-adv"
version = "0.1.0"

[dependencies]
iron = "0.4.0"
log = "0.3.6"
mime = "0.2.2"
mime_guess = "1.8.0"
time = "0.1.35"

[dev-dependencies]
hyper = "0.9.10"
iron-test = "0.4.0"
tempdir = "0.3.5"
