[package]
authors = ["Jake Goulding <jake.goulding@gmail.com>"]
name = "staticfile-adv"
version = "0.1.0"

[dependencies]
iron = "0.4.0"
log = "0.3.6"
time = "0.1.35"

[dev-dependencies]
tempdir = "0.3.5"
